trigger:
- main  # Trigger the pipeline on push to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Path to the models and app script
  modelPath: 'models/best.pt'
  appScript: 'streamlit_app/scripts.run.py'  # Path to your Streamlit app script

steps:

# Step 1: Set up Python environment
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Use Python version 3.x
    addToPath: true

# Step 2: Install dependencies from requirements.txt
- script: |
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

# Step 3: Deploy Streamlit app to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-resource-connection'  # Your Azure subscription
    appName: 'Sign Language Detectiob'  # Name of your Azure Web App
    package: '$(System.DefaultWorkingDirectory)'  # Path to the app's root directory
    deploymentMethod: 'auto'

# Step 4: (Optional) Publish artifacts for later use
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'streamlit-app'
    publishLocation: 'Container'

# Step 5: Clean up Python environment (optional)
- script: |
    pip uninstall -y -r requirements.txt
  displayName: 'Clean up Python environment'
