trigger:
- main  # Trigger the pipeline when changes are pushed to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Define paths to model and other resources
  modelPath: 'models/best.pt'
  appPath: 'streamlit_app/streamlit.py'  # Path to the Streamlit app script

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Use Python version 3.x
    addToPath: true

- script: |
    # Install required dependencies for the app using pip
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
    ArtifactName: 'sign_language_app'

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'azure-resource-connection'
    appName: 'Sign Language Detection'
    imageName: 'sign-language-app:latest'
    containers: |
      - image: 'sign-language-app:latest'

- script: |
    # Deploy the Streamlit app to Azure Web App using Docker or directly
    docker build -t sign-language-app .
    docker push sign-language-app
  displayName: 'Deploy Streamlit App'
